version: '3.3'

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: wg_forge_db
      POSTGRES_USER: wg_forge
      POSTGRES_PASSWORD: 42a
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    command: flask run --host=0.0.0.0 --port=8000 --reload
    env_file: .env
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 60s
      interval: 5s
      retries: 30
