version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - "35433:5432"

  app:
    image: python:3.11.2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: bash -c "python -m gunicorn -w 1 -b 0.0.0.0:8000 main:app"
