version: '3.3'

services:
  postgres:
    image: postgres:14.2-alpine
    env_file: .env
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5466:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql


  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    command: python -m gunicorn catbots_api.app:app -w 4
    env_file: .env
    depends_on:
      - postgres
