version: '3.8'

services:
postgres:
    image: postgres:latest
    volumes:
        - /var/lib/postgres
    environment:
        POSTGRES_DB: wg_forge_db
        POSTGRES_USER: wg_forge
        POSTGRES_PASSWORD: 42a



  app:
    image: yzh44yzh/wg_forge_backend_env:1.1
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: