version: '3.8'

services:

  postgres:
      image: postgres:latest
      volumes:
          - postgres_data:/var/lib/postgresql
      env_file: .env
      ports:
        - "35432:5432"

  app:

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  postgres_data: