version: '3.3'

services:
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    command: flask run --host=0.0.0.0 --port=8000 --reload
    env_file: .env
    depends_on:
      - postgres
