version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - "35432:5432"

  app:
    image: python:3.11.2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - 8080:8000
    command: bash -c "gunicorn -w 1 -b 0.0.0.0:8000 main:app"

volumes:
  postgres_data:
